# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout.addWidget(self.pushButton_search, 0, 1, 1, 1)
        self.lineEdit_symbol_search = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_symbol_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_symbol_search.setObjectName("lineEdit_symbol_search")
        self.gridLayout.addWidget(self.lineEdit_symbol_search, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tableView_symbol = QtWidgets.QTableView(self.groupBox)
        self.tableView_symbol.setMinimumSize(QtCore.QSize(0, 200))
        self.tableView_symbol.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_symbol.setSortingEnabled(True)
        self.tableView_symbol.setObjectName("tableView_symbol")
        self.tableView_symbol.horizontalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableView_symbol)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 200))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, 300, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Apple Color Emoji")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStatusTip("")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("Symbol")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Apple Color Emoji")
        self.lineEdit.setFont(font)
        self.lineEdit.setStatusTip("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("Symbol")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.comboBox_forex = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_forex.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_forex.setObjectName("comboBox_forex")
        self.comboBox_forex.addItem("")
        self.comboBox_forex.addItem("")
        self.comboBox_forex.addItem("")
        self.comboBox_forex.addItem("")
        self.comboBox_forex.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_forex, 3, 2, 1, 1)
        self.comboBox_interval = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_interval.setObjectName("comboBox_interval")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_interval, 3, 3, 1, 1)
        self.lineEdit_symbol_input_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_symbol_input_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_symbol_input_1.setObjectName("lineEdit_symbol_input_1")
        self.gridLayout_2.addWidget(self.lineEdit_symbol_input_1, 1, 1, 1, 1)
        self.lineEdit_symbol_input_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_symbol_input_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_symbol_input_2.setObjectName("lineEdit_symbol_input_2")
        self.gridLayout_2.addWidget(self.lineEdit_symbol_input_2, 2, 1, 1, 1)
        self.pushButton_refresh = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_refresh.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.gridLayout_2.addWidget(self.pushButton_refresh, 0, 2, 1, 1)
        self.comboBox_stock = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_stock.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_stock.setObjectName("comboBox_stock")
        self.comboBox_stock.addItem("")
        self.comboBox_stock.addItem("")
        self.comboBox_stock.addItem("")
        self.comboBox_stock.addItem("")
        self.comboBox_stock.addItem("")
        self.comboBox_stock.addItem("")
        self.comboBox_stock.addItem("")
        self.comboBox_stock.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_stock, 3, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tableView_main = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_main.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_main.setObjectName("tableView_main")
        self.verticalLayout_3.addWidget(self.tableView_main)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_compare = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_compare.setEnabled(True)
        self.groupBox_compare.setMinimumSize(QtCore.QSize(1000, 200))
        self.groupBox_compare.setAutoFillBackground(False)
        self.groupBox_compare.setObjectName("groupBox_compare")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_compare)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setContentsMargins(0, -1, 600, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_refresh_compare = QtWidgets.QPushButton(self.groupBox_compare)
        self.pushButton_refresh_compare.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_refresh_compare.setObjectName("pushButton_refresh_compare")
        self.gridLayout_3.addWidget(self.pushButton_refresh_compare, 0, 0, 1, 1)
        self.lineEdit_change_input_compare = QtWidgets.QLineEdit(self.groupBox_compare)
        self.lineEdit_change_input_compare.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_change_input_compare.setObjectName("lineEdit_change_input_compare")
        self.gridLayout_3.addWidget(self.lineEdit_change_input_compare, 2, 1, 1, 1)
        self.lineEdit_compare_change = QtWidgets.QLineEdit(self.groupBox_compare)
        self.lineEdit_compare_change.setEnabled(True)
        self.lineEdit_compare_change.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Apple Color Emoji")
        self.lineEdit_compare_change.setFont(font)
        self.lineEdit_compare_change.setStatusTip("")
        self.lineEdit_compare_change.setInputMask("")
        self.lineEdit_compare_change.setText("Change (%)")
        self.lineEdit_compare_change.setFrame(True)
        self.lineEdit_compare_change.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_compare_change.setReadOnly(True)
        self.lineEdit_compare_change.setObjectName("lineEdit_compare_change")
        self.gridLayout_3.addWidget(self.lineEdit_compare_change, 2, 0, 1, 1)
        self.lineEdit_symbol_input_compare = QtWidgets.QLineEdit(self.groupBox_compare)
        self.lineEdit_symbol_input_compare.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_symbol_input_compare.setObjectName("lineEdit_symbol_input_compare")
        self.gridLayout_3.addWidget(self.lineEdit_symbol_input_compare, 1, 1, 1, 1)
        self.lineEdit_compare_symbol_1 = QtWidgets.QLineEdit(self.groupBox_compare)
        self.lineEdit_compare_symbol_1.setEnabled(True)
        self.lineEdit_compare_symbol_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Apple Color Emoji")
        self.lineEdit_compare_symbol_1.setFont(font)
        self.lineEdit_compare_symbol_1.setStatusTip("")
        self.lineEdit_compare_symbol_1.setInputMask("")
        self.lineEdit_compare_symbol_1.setText("Symbol")
        self.lineEdit_compare_symbol_1.setFrame(True)
        self.lineEdit_compare_symbol_1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_compare_symbol_1.setReadOnly(True)
        self.lineEdit_compare_symbol_1.setObjectName("lineEdit_compare_symbol_1")
        self.gridLayout_3.addWidget(self.lineEdit_compare_symbol_1, 1, 0, 1, 1)
        self.pushButton_monitor_compare = QtWidgets.QPushButton(self.groupBox_compare)
        self.pushButton_monitor_compare.setObjectName("pushButton_monitor_compare")
        self.gridLayout_3.addWidget(self.pushButton_monitor_compare, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.tableWidget_compare = QtWidgets.QTableWidget(self.groupBox_compare)
        self.tableWidget_compare.setObjectName("tableWidget_compare")
        self.tableWidget_compare.setColumnCount(0)
        self.tableWidget_compare.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_compare)
        self.verticalLayout_6.addWidget(self.groupBox_compare)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Symbol Search"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Main"))
        self.radioButton_2.setText(_translate("MainWindow", "Forex"))
        self.radioButton.setText(_translate("MainWindow", "Stock"))
        self.comboBox_forex.setItemText(0, _translate("MainWindow", "exchange_rate"))
        self.comboBox_forex.setItemText(1, _translate("MainWindow", "forex_intraday"))
        self.comboBox_forex.setItemText(2, _translate("MainWindow", "forex_daily"))
        self.comboBox_forex.setItemText(3, _translate("MainWindow", "forex_weekly"))
        self.comboBox_forex.setItemText(4, _translate("MainWindow", "forex_monthly"))
        self.comboBox_interval.setItemText(0, _translate("MainWindow", "1min"))
        self.comboBox_interval.setItemText(1, _translate("MainWindow", "5min"))
        self.comboBox_interval.setItemText(2, _translate("MainWindow", "15min"))
        self.comboBox_interval.setItemText(3, _translate("MainWindow", "30min"))
        self.comboBox_interval.setItemText(4, _translate("MainWindow", "60min"))
        self.pushButton_refresh.setText(_translate("MainWindow", "Refresh"))
        self.comboBox_stock.setItemText(0, _translate("MainWindow", "stock_intraday"))
        self.comboBox_stock.setItemText(1, _translate("MainWindow", "stock_daily"))
        self.comboBox_stock.setItemText(2, _translate("MainWindow", "stock_daily_adjusted"))
        self.comboBox_stock.setItemText(3, _translate("MainWindow", "stock_weekly"))
        self.comboBox_stock.setItemText(4, _translate("MainWindow", "stock_weekly_adjusted"))
        self.comboBox_stock.setItemText(5, _translate("MainWindow", "stock_monthly"))
        self.comboBox_stock.setItemText(6, _translate("MainWindow", "stock_monthly_adjusted"))
        self.comboBox_stock.setItemText(7, _translate("MainWindow", "stock_quote_endpoint"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Stat"))
        self.groupBox_compare.setTitle(_translate("MainWindow", "Compare"))
        self.pushButton_refresh_compare.setText(_translate("MainWindow", "Search"))
        self.pushButton_monitor_compare.setText(_translate("MainWindow", "Monitor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Compare"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
